    <footer>
        <h2>Citations:</h2>
        <ul>
            <li><a href="https://commons.wikimedia.org/w/index.php?curid=70653074">Logo Attribution</a></li>
            <li><a href="https://disneyworld.disney.go.com/admission/tickets/">Disney World Icons Attribution</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Magic_Kingdom">Magic Kingdom Image and Content</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Epcot">Epcot Image and Content</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Disney%27s_Hollywood_Studios">Hollywood Studios Image and Content</a></li>
            <li><a href="https://en.wikipedia.org/wiki/Disney%27s_Animal_Kingdom">Animal Kingdom Image and Content</a></li>
        </ul>
        Amanda O'Donnell CSC 174 Midterm Project
    </footer>
</body>
</html>